# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: Liuhuaye020516!
  # Jackson配置
  jackson:
    serialization:
      fail-on-empty-beans: false

# MyBatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tBqPPqyqT3FErJzXL8d
    access-key-secret: XS85hpn06TMFPWrR6JPvRDpJyNHcr4
    bucket-name: spring-coming516

# 服务器配置
server:
  port: 8080

